name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      TEST_USER_PASS: ${{ secrets.INTEGRATION_TESTS_USER_PASS }}
    runs-on: ubuntu-16.04
    strategy:
      fail-fast: false
      matrix:
        jdk: [8, 9, 10, 11, 12, 13]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}
      - name: Check gradle version
        run: "./gradlew --version"
      - name: gradle check
        run: "./gradlew check -i"
      - name: Notify slack fail
        uses: voxmedia/github-action-slack-notify-build@v1
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: C414367GV
          status: FAILED
          color: danger

  build-seven:
    env:
      TEST_USER_PASS: ${{ secrets.INTEGRATION_TESTS_USER_PASS }}
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Set up JDK 7
        uses: actions/setup-java@v1
        with:
          java-version: 7
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Check gradle version
        run: "./gradlew --version"
      - name: gradle check
        run: "./gradlew testsOn7"

  publish:
    needs: build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish package
        run: "./gradlew publish"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  notify-success:
    needs: [build, publish]
    runs-on: ubuntu-latest
    steps:
      - name: Notify slack success
        uses: voxmedia/github-action-slack-notify-build@v1
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        with:
          channel_id: C414367GV
          status: SUCCESS
          color: good
